### ISSUE TITLE
How can I get the linodes list

### ISSUE THREAD

**Issue by RajuSPR** [lloydsparkes/linode-api#1]
I had go through this API. But I don't know how can I get the linodes list. Which method I have to use and how to pass the parameters. Where I have to configure the personal access token. Please help me.

**Comment by lloydsparkes** [comment]
Hi,

This library is not maintained any more, and does not support the method you are looking for.

I suggest you use: 

https://github.com/AustinWise/Austin.Linode

Thanks

Lloyd
